// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0pd4tAuh-zEFLEq3mdbwYH3PYjB0pW9g',
    appId: '1:957934608319:web:df909e70fd5b6eb17e4b0a',
    messagingSenderId: '957934608319',
    projectId: 'chat-app-re-b3550',
    authDomain: 'chat-app-re-b3550.firebaseapp.com',
    storageBucket: 'chat-app-re-b3550.firebasestorage.app',
    measurementId: 'G-6EQY84P5GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrEW1PdlFVS6qlz6B6aTZDZd_aIfhKhiI',
    appId: '1:957934608319:android:3b9af6e17699ec0c7e4b0a',
    messagingSenderId: '957934608319',
    projectId: 'chat-app-re-b3550',
    storageBucket: 'chat-app-re-b3550.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMN3IHao6C96mWb3l3KFaGVplFS5aJ9BY',
    appId: '1:957934608319:ios:f0824b6634caf3a87e4b0a',
    messagingSenderId: '957934608319',
    projectId: 'chat-app-re-b3550',
    storageBucket: 'chat-app-re-b3550.firebasestorage.app',
    iosBundleId: 'com.example.chatAppRe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMN3IHao6C96mWb3l3KFaGVplFS5aJ9BY',
    appId: '1:957934608319:ios:f0824b6634caf3a87e4b0a',
    messagingSenderId: '957934608319',
    projectId: 'chat-app-re-b3550',
    storageBucket: 'chat-app-re-b3550.firebasestorage.app',
    iosBundleId: 'com.example.chatAppRe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0pd4tAuh-zEFLEq3mdbwYH3PYjB0pW9g',
    appId: '1:957934608319:web:147d28bb55615e667e4b0a',
    messagingSenderId: '957934608319',
    projectId: 'chat-app-re-b3550',
    authDomain: 'chat-app-re-b3550.firebaseapp.com',
    storageBucket: 'chat-app-re-b3550.firebasestorage.app',
    measurementId: 'G-PDC5SDZVLS',
  );
}
